### ISSUE TITLE
Multiple functions within the same assembly

### ISSUE THREAD

**Issue by mcollins4551** [lindydonna/FunctionsAsWebProject#4]
Hello.  Should I be able to create multiple functions within the same assembly?  i.e.
FunctionProj
->Function1
---->Function.cs
---->function.json
->Function2
---->Function.cs
---->function.json

When I try to do this, the cli only seems to pick up one of the functions when I try to debug.  Just wondering if I may be doing something wrong or if this isn't supported and I need to create each function in a separate project.  

Seems like a lot of extra boilerplate to have to create a separate project for each function.

Thanks.

**Comment by lindydonna** [comment]
@mcollins4551 Yes, just edit the "entryPoint" property to point to the fully-qualified class name for your other functions.
