### ISSUE TITLE
Function not available at expected URL

### ISSUE THREAD

**Issue by steveculshaw** [lindydonna/FunctionsAsWebProject#5]
I've download a clean copy of the code, deployed to my test Azure account, but doesn't appear to be working ... more accurately, I can't get it to work  :-)

I'm trying the URL ... https://xxx.azurewebsites.net/api/HelloHttpTrigger ... in a similar vein to the usual Function App calls

From a "standard" Function App I get the expected "Please pass a name on the query string or in the request body" 

But from the pre-compiled, just get a 404

**Comment by lindydonna** [comment]
Cc @fabiocav

**Comment by GregLevenhagen** [comment]
Any update?

**Comment by lindydonna** [comment]
@GregLevenhagen This model of running precompiled functions is the manual method. You should try out our Visual Studio 2017 tooling: https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs
